# ビルド、プッシュ、デプロイのステップを定義
steps:
  # -----------------------------------------------------
  # Step 1: Docker イメージをビルドする
  # -----------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_IMAGE_NAME}:$COMMIT_SHA'
      - '.'
    id: Build

  # -----------------------------------------------------
  # Step 2: ビルドしたイメージをArtifact Registryにプッシュする
  # -----------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_IMAGE_NAME}:$COMMIT_SHA'
    waitFor: ['Build']
    id: Push

  # -----------------------------------------------------
  # Step 3: コンテナイメージをCloud Runにデプロイする
  # -----------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}' # デプロイするCloud Runサービス名
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_IMAGE_NAME}:$COMMIT_SHA' # デプロイするイメージ
      - '--region=${_REGION}' # デプロイ先のリージョン
      # ★★★ ここは Cloud Run "実行" SA を指定 (変更なし) ★★★
      - '--service-account=${_RUN_SERVICE_ACCOUNT_EMAIL}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      # ★★★ Secret Managerから環境変数を設定 (変更なし) ★★★
      - '--update-secrets=FIREBASE_WEB_CONFIG_JSON=${_SECRET_WEB_CONFIG}:latest,ALLOWED_USERS_STR=${_SECRET_ALLOWED_USERS}:latest'
      # 必要に応じて他のオプションを追加
      # - '--memory=512Mi'
      # - '--cpu=1'
    waitFor: ['Push']
    id: Deploy

# ビルドされるイメージを指定
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_IMAGE_NAME}:$COMMIT_SHA'

# ビルド実行時に置換される変数 (デフォルト値)
substitutions:
  _REGION: 'asia-northeast1' # ★ あなたのGCPリージョン
  _ARTIFACT_REPO: 'streamlit-chat-repo' # ★ あなたのArtifact Registryリポジトリ名
  _IMAGE_NAME: 'streamlit-chat-app' # ★ 任意のイメージ名
  _SERVICE_NAME: 'streamlit-chat-app' # ★ あなたのCloud Runサービス名
  # ★★★ Cloud Run "実行" SAのEmail ★★★
  _RUN_SERVICE_ACCOUNT_EMAIL: 'cloudrun-chat-runner@${PROJECT_ID}.iam.gserviceaccount.com' # ★ あなたのCloud Run実行SAのEmail (プロジェクトID部分はCloud Buildが展開)
  # ★★★ カスタム Cloud Build SA の Email を追加 ★★★
  _CUSTOM_CB_SA_EMAIL: 'cloudbuild-sa@${PROJECT_ID}.iam.gserviceaccount.com' # ★ あなたが作成したカスタムSAのEmail (プロジェクトID部分はCloud Buildが展開)
  # --- Secret Managerのシークレット名 ---
  _SECRET_WEB_CONFIG: 'firebase-web-config-json' # ★ あなたが作成したSecretの名前
  _SECRET_ALLOWED_USERS: 'allowed-users-string' # ★ あなたが作成したSecretの名前

# ビルドオプション
options:
  logging: CLOUD_LOGGING_ONLY
  # ★★★ ビルドを実行するサービスアカウントとしてカスタムSAを指定 ★★★
  serviceAccount: ${_CUSTOM_CB_SA_EMAIL}
  # machineType: 'N1_HIGHCPU_8'
