# ビルド、プッシュ、デプロイのステップを定義
steps:
  # -----------------------------------------------------
  # Step 1: Docker イメージをビルドする
  # -----------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_IMAGE_NAME}:$COMMIT_SHA'
      - '.'
    id: Build

  # -----------------------------------------------------
  # Step 2: ビルドしたイメージをArtifact Registryにプッシュする
  # -----------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_IMAGE_NAME}:$COMMIT_SHA'
    waitFor: ['Build']
    id: Push

  # -----------------------------------------------------
  # Step 3: コンテナイメージをCloud Runにデプロイする
  # -----------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}' # デプロイするCloud Runサービス名
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_IMAGE_NAME}:$COMMIT_SHA' # デプロイするイメージ
      - '--region=${_REGION}' # デプロイ先のリージョン
      - '--service-account=${_RUN_SERVICE_ACCOUNT_EMAIL}' # Cloud Run実行サービスアカウント
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--update-secrets=FIREBASE_WEB_CONFIG_JSON=${_SECRET_WEB_CONFIG}:latest,ALLOWED_USERS_STR=${_SECRET_ALLOWED_USERS}:latest' # Secret Manager参照
      # - '--memory=512Mi'
      # - '--cpu=1'
    waitFor: ['Push']
    id: Deploy

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_IMAGE_NAME}:$COMMIT_SHA'

substitutions:
  _REGION: 'asia-northeast1'
  _ARTIFACT_REPO: 'streamlit-chat-repo'
  _IMAGE_NAME: 'streamlit-chat-app'
  _SERVICE_NAME: 'streamlit-chat-app'
  _RUN_SERVICE_ACCOUNT_EMAIL: 'cloudrun-chat-runner@${PROJECT_ID}.iam.gserviceaccount.com'
  _SECRET_WEB_CONFIG: 'firebase-web-config-json'
  _SECRET_ALLOWED_USERS: 'allowed-users-string'
  # _CUSTOM_CB_SA_EMAIL は削除
# options: セクション全体を削除
