# ビルド、プッシュ、デプロイのステップを定義
steps:
  # -----------------------------------------------------
  # Step 1: Docker イメージをビルドする
  # -----------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_IMAGE_NAME}:$COMMIT_SHA'
      - '.'
    id: Build

  # -----------------------------------------------------
  # Step 2: ビルドしたイメージをArtifact Registryにプッシュする
  # -----------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_IMAGE_NAME}:$COMMIT_SHA'
    waitFor: ['Build']
    id: Push

  # -----------------------------------------------------
  # Step 3: コンテナイメージをCloud Runにデプロイする
  # -----------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}' # デプロイするCloud Runサービス名
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_IMAGE_NAME}:$COMMIT_SHA' # デプロイするイメージ
      - '--region=${_REGION}' # デプロイ先のリージョン
      - '--service-account=${_RUN_SERVICE_ACCOUNT_EMAIL}' # Cloud Run実行サービスアカウント
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--update-secrets=FIREBASE_WEB_CONFIG_JSON=${_SECRET_WEB_CONFIG}:latest,ALLOWED_USERS_STR=${_SECRET_ALLOWED_USERS}:latest' # Secret Manager参照
      # - '--memory=512Mi'
      # - '--cpu=1'
    waitFor: ['Push']
    id: Deploy

# ビルドされるイメージを指定
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_IMAGE_NAME}:$COMMIT_SHA'

# ビルド実行時に置換される変数 (デフォルト値)
substitutions:
  _REGION: 'asia-northeast1' # ★ あなたのGCPリージョン
  _ARTIFACT_REPO: 'streamlit-chat-repo' # ★ あなたのArtifact Registryリポジトリ名
  _IMAGE_NAME: 'streamlit-chat-app' # ★ 任意のイメージ名
  _SERVICE_NAME: 'streamlit-chat-app' # ★ あなたのCloud Runサービス名
  # ★★★ Cloud Run "実行" SAのEmail ★★★
  _RUN_SERVICE_ACCOUNT_EMAIL: 'cloudrun-chat-runner@${PROJECT_ID}.iam.gserviceaccount.com' # ★ あなたのCloud Run実行SA
  # ★★★ カスタム Cloud Build SA の Email (重複削除) ★★★
  _CUSTOM_CB_SA_EMAIL: 'cloudbuild-sa@${PROJECT_ID}.iam.gserviceaccount.com' # ★ あなたが作成したカスタムSA
  # --- Secret Managerのシークレット名 ---
  _SECRET_WEB_CONFIG: 'firebase-web-config-json' # ★ あなたが作成したSecretの名前
  _SECRET_ALLOWED_USERS: 'allowed-users-string' # ★ あなたが作成したSecretの名前
  # ★★★ 重複していた行を削除 ★★★
  # _CUSTOM_CB_SA_EMAIL: 'cloudbuild-sa@${PROJECT_ID}.iam.gserviceaccount.com' # ← この行を削除

# ビルドオプション
# ★★★ options: は行頭から ★★★
options:
  # ★★★ serviceAccount は options: の下にインデント (スペース2つ) ★★★
  serviceAccount: ${_CUSTOM_CB_SA_EMAIL}
  # logging: CLOUD_LOGGING_ONLY # 必要であればインデントして追加
  # machineType: 'N1_HIGHCPU_8' # 必要であればインデントして追加
